### ISSUE TITLE
Crashing when holding fishing rod in hand MP

### ISSUE THREAD

**Issue by Shadow77388** [TehPers/StardewValleyMods#2]
whenever i have a fishing rod in my hand the game crashed on sleep. i know you havnt released the mod yet but i thought this might help fix some bugs.(compiled myself) fishing overhaul for MP1.3.9 of stardew beta.

**Comment by TehPers** [comment]
Fixed this a while back. The mod no longer uses a custom item class, which was causing issues in multiplayer because the class wasn't playing nicely with the network code they had.
