### ISSUE TITLE
Seaweed, algae, and void mayonnaise uncatchable

### ISSUE THREAD

**Issue by TehPers** [TehPers/StardewValleyMods#9]
Check if these are catchable in the current version. If not, make them catchable.

**Comment by snwflake** [comment]
Welp, that saves the time writing a ticket.

Is this something you consider implementing in the near future?
I'd otherwise do some research about the drop rates and send a PR.

**Comment by snwflake** [comment]
Removing the following check solves this:
```cs
if (fishInfo[1] == "5") // Junk item
    continue;
````
https://github.com/TehPers/StardewValleyMods/blob/master/FishingOverhaul/Configs/ConfigFish.cs#L63

**Comment by TehPers** [comment]
Fixed in v3.0.
